version: '3.8'

services:
  credential-manager:
    build: .
    container_name: secure-credential-manager
    ports:
      - "8502:8501"
    volumes:
      # Mounts the database file for data persistence
      - ./credentials.db:/app/credentials.db
      # Mounts the local backups folder (optional but good practice)
      - ./backups:/app/backups
      # CRITICAL: Mount Google OAuth files into the container
      - ./client_secrets.json:/app/client_secrets.json
      - ./token.json:/app/token.json
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - credential-net

networks:
  credential-net:
    driver: bridge